{{- if and .Values.partnerSchema.enabled .Values.partnerSchema.content }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hyperfleet-api.fullname" . }}-partner-schema
  labels:
    {{- include "hyperfleet-api.labels" . | nindent 4 }}
data:
  {{ base .Values.partnerSchema.mountPath }}: |
    {{- .Values.partnerSchema.content | nindent 4 }}
{{- end }}
